//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4959
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STARTLibrary.accesspointService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StartException", Namespace="http://busdox.org/2010/02/channel/fault")]
    [System.SerializableAttribute()]
    public partial class StartException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string actionField;
        
        private string faultcodeField;
        
        private string faultstringField;
        
        private string detailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string action {
            get {
                return this.actionField;
            }
            set {
                if ((object.ReferenceEquals(this.actionField, value) != true)) {
                    this.actionField = value;
                    this.RaisePropertyChanged("action");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string faultcode {
            get {
                return this.faultcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.faultcodeField, value) != true)) {
                    this.faultcodeField = value;
                    this.RaisePropertyChanged("faultcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string faultstring {
            get {
                return this.faultstringField;
            }
            set {
                if ((object.ReferenceEquals(this.faultstringField, value) != true)) {
                    this.faultstringField = value;
                    this.RaisePropertyChanged("faultstring");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string details {
            get {
                return this.detailsField;
            }
            set {
                if ((object.ReferenceEquals(this.detailsField, value) != true)) {
                    this.detailsField = value;
                    this.RaisePropertyChanged("details");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.w3.org/2009/02/ws-tra", ConfigurationName = "STARTLibrary.accesspointService.Resource")]
    public interface Resource {
        
        // CODEGEN: Generating message contract since the operation Get is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.w3.org/2009/02/ws-tra/Get", ReplyAction="http://www.w3.org/2009/02/ws-tra/GetResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        STARTLibrary.accesspointService.GetResponse1 Get(STARTLibrary.accesspointService.GetRequest request);
        
        // CODEGEN: Generating message contract since the operation Put is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.w3.org/2009/02/ws-tra/Put", ReplyAction="http://www.w3.org/2009/02/ws-tra/PutResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        STARTLibrary.accesspointService.PutResponse1 Put(STARTLibrary.accesspointService.PutRequest request);
        
        // CODEGEN: Generating message contract since the operation Delete is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.w3.org/2009/02/ws-tra/Delete", ReplyAction="http://www.w3.org/2009/02/ws-tra/DeleteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        STARTLibrary.accesspointService.DeleteResponse1 Delete(STARTLibrary.accesspointService.DeleteRequest request);
        
        // CODEGEN: Generating message contract since the operation Create is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.w3.org/2009/02/ws-tra/Create", ReplyAction="http://www.w3.org/2009/02/ws-tra/CreateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(STARTLibrary.accesspointService.StartException), Action="http://busdox.org/2010/02/channel/fault", Name="StartException", Namespace="http://busdox.org/2010/02/channel/fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        STARTLibrary.accesspointService.CreateResponse1 Create(STARTLibrary.accesspointService.CreateRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2009/02/ws-tra")]
    public partial class Get : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://busdox.org/transport/identifiers/1.0/")]
    public partial class ProcessIdentifierType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string schemeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string scheme {
            get {
                return this.schemeField;
            }
            set {
                this.schemeField = value;
                this.RaisePropertyChanged("scheme");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://busdox.org/transport/identifiers/1.0/")]
    public partial class DocumentIdentifierType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string schemeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string scheme {
            get {
                return this.schemeField;
            }
            set {
                this.schemeField = value;
                this.RaisePropertyChanged("scheme");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://busdox.org/transport/identifiers/1.0/")]
    public partial class ParticipantIdentifierType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string schemeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string scheme {
            get {
                return this.schemeField;
            }
            set {
                this.schemeField = value;
                this.RaisePropertyChanged("scheme");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
    public partial class MetadataType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
    public partial class ReferenceParametersType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
    public partial class AttributedURIType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="anyURI")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
    public partial class EndpointReferenceType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AttributedURIType addressField;
        
        private ReferenceParametersType referenceParametersField;
        
        private MetadataType metadataField;
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AttributedURIType Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ReferenceParametersType ReferenceParameters {
            get {
                return this.referenceParametersField;
            }
            set {
                this.referenceParametersField = value;
                this.RaisePropertyChanged("ReferenceParameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public MetadataType Metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
                this.RaisePropertyChanged("Metadata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=3)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2009/02/ws-tra")]
    public partial class GetResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.w3.org/2009/02/ws-tra", Order=0)]
        public STARTLibrary.accesspointService.Get Get;
        
        public GetRequest() {
        }
        
        public GetRequest(STARTLibrary.accesspointService.Get Get) {
            this.Get = Get;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.w3.org/2009/02/ws-tra", Order=0)]
        public STARTLibrary.accesspointService.GetResponse GetResponse;
        
        public GetResponse1() {
        }
        
        public GetResponse1(STARTLibrary.accesspointService.GetResponse GetResponse) {
            this.GetResponse = GetResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2009/02/ws-tra")]
    public partial class Put : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2009/02/ws-tra")]
    public partial class PutResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.w3.org/2009/02/ws-tra", Order=0)]
        public STARTLibrary.accesspointService.Put Put;
        
        public PutRequest() {
        }
        
        public PutRequest(STARTLibrary.accesspointService.Put Put) {
            this.Put = Put;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.w3.org/2009/02/ws-tra", Order=0)]
        public STARTLibrary.accesspointService.PutResponse PutResponse;
        
        public PutResponse1() {
        }
        
        public PutResponse1(STARTLibrary.accesspointService.PutResponse PutResponse) {
            this.PutResponse = PutResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2009/02/ws-tra")]
    public partial class Delete : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2009/02/ws-tra")]
    public partial class DeleteResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.w3.org/2009/02/ws-tra", Order=0)]
        public STARTLibrary.accesspointService.Delete Delete;
        
        public DeleteRequest() {
        }
        
        public DeleteRequest(STARTLibrary.accesspointService.Delete Delete) {
            this.Delete = Delete;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.w3.org/2009/02/ws-tra", Order=0)]
        public STARTLibrary.accesspointService.DeleteResponse DeleteResponse;
        
        public DeleteResponse1() {
        }
        
        public DeleteResponse1(STARTLibrary.accesspointService.DeleteResponse DeleteResponse) {
            this.DeleteResponse = DeleteResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2009/02/ws-tra")]
    public partial class Create : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2009/02/ws-tra")]
    public partial class CreateResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private EndpointReferenceType[] resourceCreatedField;
        
        private System.Xml.XmlElement anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("EndpointReference", Namespace="http://www.w3.org/2005/08/addressing", IsNullable=false)]
        public EndpointReferenceType[] ResourceCreated {
            get {
                return this.resourceCreatedField;
            }
            set {
                this.resourceCreatedField = value;
                this.RaisePropertyChanged("ResourceCreated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://busdox.org/transport/identifiers/1.0/")]
        public string MessageIdentifier;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://busdox.org/transport/identifiers/1.0/")]
        public string ChannelIdentifier;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://busdox.org/transport/identifiers/1.0/")]
        public STARTLibrary.accesspointService.ParticipantIdentifierType RecipientIdentifier;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://busdox.org/transport/identifiers/1.0/")]
        public STARTLibrary.accesspointService.ParticipantIdentifierType SenderIdentifier;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://busdox.org/transport/identifiers/1.0/")]
        public STARTLibrary.accesspointService.DocumentIdentifierType DocumentIdentifier;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://busdox.org/transport/identifiers/1.0/")]
        public STARTLibrary.accesspointService.ProcessIdentifierType ProcessIdentifier;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.w3.org/2009/02/ws-tra", Order=0)]
        public STARTLibrary.accesspointService.Create Create;
        
        public CreateRequest() {
        }
        
        public CreateRequest(string MessageIdentifier, string ChannelIdentifier, STARTLibrary.accesspointService.ParticipantIdentifierType RecipientIdentifier, STARTLibrary.accesspointService.ParticipantIdentifierType SenderIdentifier, STARTLibrary.accesspointService.DocumentIdentifierType DocumentIdentifier, STARTLibrary.accesspointService.ProcessIdentifierType ProcessIdentifier, STARTLibrary.accesspointService.Create Create) {
            this.MessageIdentifier = MessageIdentifier;
            this.ChannelIdentifier = ChannelIdentifier;
            this.RecipientIdentifier = RecipientIdentifier;
            this.SenderIdentifier = SenderIdentifier;
            this.DocumentIdentifier = DocumentIdentifier;
            this.ProcessIdentifier = ProcessIdentifier;
            this.Create = Create;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.w3.org/2009/02/ws-tra", Order=0)]
        public STARTLibrary.accesspointService.CreateResponse CreateResponse;
        
        public CreateResponse1() {
        }
        
        public CreateResponse1(STARTLibrary.accesspointService.CreateResponse CreateResponse) {
            this.CreateResponse = CreateResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ResourceChannel : STARTLibrary.accesspointService.Resource, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ResourceClient : System.ServiceModel.ClientBase<STARTLibrary.accesspointService.Resource>, STARTLibrary.accesspointService.Resource {
        
        public ResourceClient() {
        }
        
        public ResourceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ResourceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResourceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResourceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        STARTLibrary.accesspointService.GetResponse1 STARTLibrary.accesspointService.Resource.Get(STARTLibrary.accesspointService.GetRequest request) {
            return base.Channel.Get(request);
        }
        
        public STARTLibrary.accesspointService.GetResponse Get(STARTLibrary.accesspointService.Get Get1) {
            STARTLibrary.accesspointService.GetRequest inValue = new STARTLibrary.accesspointService.GetRequest();
            inValue.Get = Get1;
            STARTLibrary.accesspointService.GetResponse1 retVal = ((STARTLibrary.accesspointService.Resource)(this)).Get(inValue);
            return retVal.GetResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        STARTLibrary.accesspointService.PutResponse1 STARTLibrary.accesspointService.Resource.Put(STARTLibrary.accesspointService.PutRequest request) {
            return base.Channel.Put(request);
        }
        
        public STARTLibrary.accesspointService.PutResponse Put(STARTLibrary.accesspointService.Put Put1) {
            STARTLibrary.accesspointService.PutRequest inValue = new STARTLibrary.accesspointService.PutRequest();
            inValue.Put = Put1;
            STARTLibrary.accesspointService.PutResponse1 retVal = ((STARTLibrary.accesspointService.Resource)(this)).Put(inValue);
            return retVal.PutResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        STARTLibrary.accesspointService.DeleteResponse1 STARTLibrary.accesspointService.Resource.Delete(STARTLibrary.accesspointService.DeleteRequest request) {
            return base.Channel.Delete(request);
        }
        
        public STARTLibrary.accesspointService.DeleteResponse Delete(STARTLibrary.accesspointService.Delete Delete1) {
            STARTLibrary.accesspointService.DeleteRequest inValue = new STARTLibrary.accesspointService.DeleteRequest();
            inValue.Delete = Delete1;
            STARTLibrary.accesspointService.DeleteResponse1 retVal = ((STARTLibrary.accesspointService.Resource)(this)).Delete(inValue);
            return retVal.DeleteResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        STARTLibrary.accesspointService.CreateResponse1 STARTLibrary.accesspointService.Resource.Create(STARTLibrary.accesspointService.CreateRequest request) {
            return base.Channel.Create(request);
        }
        
        public STARTLibrary.accesspointService.CreateResponse Create(string MessageIdentifier, string ChannelIdentifier, STARTLibrary.accesspointService.ParticipantIdentifierType RecipientIdentifier, STARTLibrary.accesspointService.ParticipantIdentifierType SenderIdentifier, STARTLibrary.accesspointService.DocumentIdentifierType DocumentIdentifier, STARTLibrary.accesspointService.ProcessIdentifierType ProcessIdentifier, STARTLibrary.accesspointService.Create Create1) {
            STARTLibrary.accesspointService.CreateRequest inValue = new STARTLibrary.accesspointService.CreateRequest();
            inValue.MessageIdentifier = MessageIdentifier;
            inValue.ChannelIdentifier = ChannelIdentifier;
            inValue.RecipientIdentifier = RecipientIdentifier;
            inValue.SenderIdentifier = SenderIdentifier;
            inValue.DocumentIdentifier = DocumentIdentifier;
            inValue.ProcessIdentifier = ProcessIdentifier;
            inValue.Create = Create1;
            STARTLibrary.accesspointService.CreateResponse1 retVal = ((STARTLibrary.accesspointService.Resource)(this)).Create(inValue);
            return retVal.CreateResponse;
        }
    }
}
